# Generated by Django 4.1.3 on 2022-11-28 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='user_field',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(blank=True, max_length=100, null=True)),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('mobile', models.IntegerField(blank=True, null=True)),
                ('otp', models.IntegerField(blank=True, null=True)),
                ('Account_number', models.IntegerField(blank=True, max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='wallet_payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(blank=True, null=True)),
                ('withdraw', models.IntegerField(blank=True, null=True)),
                ('add_money', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
