# Generated by Django 4.1.3 on 2022-11-09 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='wallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=100, null=True)),
                ('password', models.IntegerField(max_length=255, null=True)),
                ('name', models.CharField(max_length=255, null=True)),
            ],
        ),
    ]
