# Generated by Django 4.1.3 on 2022-11-10 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('walletapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wallet',
            name='password',
        ),
        migrations.AddField(
            model_name='wallet',
            name='mobile_number',
            field=models.IntegerField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='email',
            field=models.EmailField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
