# Generated by Django 4.1.3 on 2022-12-05 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('walletapp', '0002_alter_user_field_account_number'),
    ]

    operations = [
        migrations.DeleteModel(
            name='wallet_payment',
        ),
        migrations.AddField(
            model_name='user_field',
            name='add_money',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user_field',
            name='amount',
            field=models.IntegerField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='user_field',
            name='withdraw',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user_field',
            name='email',
            field=models.EmailField(blank=True, max_length=50, null=True),
        ),
    ]
