# Generated by Django 4.1.3 on 2022-11-10 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('walletapp', '0002_remove_wallet_password_wallet_mobile_number_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Login',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile', models.IntegerField(blank=True, max_length=10, null=True)),
                ('otp', models.IntegerField(blank=True, max_length=10, null=True)),
            ],
        ),
        migrations.RenameField(
            model_name='wallet',
            old_name='mobile_number',
            new_name='mobile',
        ),
    ]
