# Generated by Django 4.1.3 on 2022-11-10 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('walletapp', '0003_login_rename_mobile_number_wallet_mobile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='login',
            name='otp',
            field=models.IntegerField(blank=True, max_length=100, null=True),
        ),
    ]
