# Generated by Django 4.1.3 on 2022-11-14 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('walletapp', '0004_alter_login_otp'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Login',
        ),
        migrations.AddField(
            model_name='wallet',
            name='amount',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='wallet',
            name='otp',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='mobile',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
