# Generated by Django 4.1.3 on 2022-12-07 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('walletapp', '0004_user_field_qr_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_field',
            name='profile_image',
            field=models.ImageField(blank=True, upload_to='profileimage'),
        ),
    ]
