# Generated by Django 4.1.3 on 2022-11-15 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('walletapp', '0005_delete_login_wallet_amount_wallet_otp_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='user_field',
            fields=[
                ('email', models.EmailField(blank=True, max_length=100, null=True)),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('mobile', models.IntegerField(blank=True, null=True)),
                ('otp', models.IntegerField(blank=True, null=True)),
                ('id', models.IntegerField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='wallet_payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(blank=True, max_length=100, null=True)),
                ('withdraw', models.IntegerField(blank=True, max_length=50, null=True)),
                ('add_money', models.IntegerField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='wallet',
        ),
    ]
