# Generated by Django 4.1.3 on 2022-11-16 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('walletapp', '0006_user_field_wallet_payment_delete_wallet'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user_field',
            old_name='id',
            new_name='Acount_number',
        ),
        migrations.AlterField(
            model_name='wallet_payment',
            name='add_money',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='wallet_payment',
            name='amount',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='wallet_payment',
            name='withdraw',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
