# Generated by Django 4.1.3 on 2022-11-17 06:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('walletapp', '0007_rename_id_user_field_acount_number_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user_field',
            old_name='Acount_number',
            new_name='Account_number',
        ),
    ]
